name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
      with:
        node-version: "12.x"
    
    - name: Install dependencies
      run: |
        npm install 

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@v1.8.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: DragonOS-Community/OS_lab_tutorial
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm run docs:build
        BUILD_DIR: docs/.vuepress/dist/
